### ISSUE TITLE
[BUG] Creation of services with BTP env - failure in status check

### ISSUE THREAD

**Issue by lechnerc77** [SAP-samples/btp-setup-automator#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

CLI in general

### Current Behavior

Setup of services that take a longer setup fail when target is BTP environment.

[2023-02-16 16:17:07] INFO       : Create instance >EasyFranchiseHANADB< for service >hana-cloud< and plan >hana-free< via BTP CLI

[2023-02-16 16:17:07] RUN COMMAND: btp --format json create services/instance --subaccount 4237d0a5-6560-41c4-926d-02098f95f7d4 --offering-name hana-cloud --plan-name hana-free --name EasyFranchiseHANADB --parameters '{"data": {"edition": "cloud", "memory": 30, "serviceStopped": false, "storage": 120, "systempassword": "mySAP123", "vcpu": 0, "versionIndicator": "", "whitelistIPs": ["0.0.0.0/0"]}}'

[2023-02-16 16:17:10] ERROR      : Traceback (most recent call last):

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/home/user/./btpsa", line 42, in <module>

    myBtpUseCase.create_configured_app_subscriptions_and_services()

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/home/user/libs/python/btp_cli.py", line 1092, in create_configured_app_subscriptions_and_services

    initiateCreationOfServiceInstances(self)

 

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/home/user/libs/python/helperServiceInstances.py", line 343, in initiateCreationOfServiceInstances

    service = createServiceInstance(

 

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/home/user/libs/python/helperServiceInstances.py", line 373, in createServiceInstance

    service = create_btp_service(btpUsecase, service)

 

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/home/user/libs/python/helperEnvBTP.py", line 63, in create_btp_service

    result = convertStringToJson(p.stdout.decode())

 

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/home/user/libs/python/helperJson.py", line 115, in convertStringToJson

    jsonObject = json.loads(string)

 

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

 

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

 

NoneType: None

[2023-02-16 16:17:10] ERROR      :   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

NoneType: None

[2023-02-16 16:17:10] ERROR      : json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

NoneType: None

[2023-02-16 16:17:10] ERROR      : Expecting value: line 1 column 1 (char 0)

NoneType: None

### Expected Behavior

Execution should work like for CF environment

**Comment by lechnerc77** [comment]
Fix confirmed - will be part of next release

**Comment by lechnerc77** [comment]
Available in `main`
